version: 0.2

phases:
  pre_build: ## this is where you login to ECR
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      #- aws ecr get-login-password --region us-east-1 --profile sajigrp | docker login --username AWS --password-stdin 613952966806.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 613952966806.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 613952966806.dkr.ecr.us-east-1.amazonaws.com/youtube:latest
      - printf '[{"name":helloWorld,"imageUri":"%s"}]' 613952966806.dkr.ecr.us-east-1.amazonaws.com/youtube:lates > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
